
<!-- ***** PAGE CONTENT STARTS ***** -->


<div class="box0">

<div class="box1">
<table border="0"><tr><td valign="top">
<h2 class="green">Contact Mark Knight</h2>
<p>
<a class="white" href="mailto:<?php echo $cadenzas_business_email;?>">Email Mark Knight</a>
</p>
<p class="green">For information on the work of Mark Knight and all materials published by Strings Attached Ltd, contact:</p>
<p class="green"><b>
Strings Attached Ltd.<br>Great Skewes Cottage<br>St. Wenn<br>Bodmin<br>Cornwall<br>PL30 5PS<br>United Kingdom<br> Telephone and Fax: +44 (0)1726 890 639</b>
</p>
</td><td valign="top">
<img src="images/mknight1_200.jpg" alt="Mark Knight" align="right" width="200" height="196"><br clear="all">
<p class="smallText" align="right"> Photo: Janet Young </p>
</td></tr></table>
</div>
<!--
<div class="box1">
<p class="green">For all materials published by Strings Attached Ltd, contact:</p>
<p class="green"><b>
Strings Attached Ltd<br>
Ryders Cottage<br>
1 Molesworth Row<br>
Egloshayle<br>
Wadebridge<br>
Cornwall<br>
PL27 6HT<br>
United Kingdom
</b>
</div>
-->
</div>

