<h2>Concerto in C major for Viola, Haydn Hob.VIIb:1</h2><p> by Mark Knight</p>
<p>Mark Knight's transcription of Haydn's 'Cello Concerto in C for viola, complete with cadenzas.</p>
<table class="book">
<tr>

<td><a class="popzoom" href=""><img src="images/images/mk5.jpg" onClick="javascript: pop_zoom('images/images/mk5.jpg','Concerto in C major for Viola, Haydn Hob.VIIb:1','ISMN: M 9002001-5-0',680,900);return false;" alt="Concerto in C major for Viola, Haydn Hob.VIIb:1, images/images/mk5.jpg" height="240"/>
<br/><p>ISMN: M 9002001-5-0</p></a>
</td>
<td><a class="popzoom" href=""><img src="images/mknight_haydn_image_240_290.jpg" onClick="javascript: pop_zoom('images/mknight_haydn_image_240_290.jpg','Concerto in C major for Viola, Haydn Hob.VIIb:1','Illustration by Jackie Griffin',680,900);return false;" alt="Concerto in C major for Viola, Haydn Hob.VIIb:1, images/mknight_haydn_image_240_290.jpg" height="240"/>
<br/><p>Illustration by Jackie Griffin</p></a>
</td>
<td><a class="popzoom" href=""><img src="" onClick="javascript: pop_zoom('','Concerto in C major for Viola, Haydn Hob.VIIb:1','Sample page Mark Knight',680,900);return false;" alt="Concerto in C major for Viola, Haydn Hob.VIIb:1, " height="240"/>
<br/><p>Sample page Mark Knight</p></a>
</td>
</tr></table>
<br/>
<p>£15.95 + postage and packing</p> <p>ISMN:M 9002001-5-0<br/>Illustration: Jackie Griffin</p>

<h2>Purchase with PayPal</h2>
<div class="PayPalPayNow">
<form name="_xclick" target="paypal" action="https://www.paypal.co.uk/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_cart">
<input type="hidden" name="business" value="stringsattachedltd@googlemail.com">
<input type="hidden" name="currency_code" value="GBP">
<input type="hidden" name="item_name" value="Cadenza Haydn Viola, ISMN:M 9002001-5-0">
<input type="hidden" name="amount" value="15.95">
<br/>
<select name="quantity">
  <option value="1">1</option>
  <option value="2">2</option>

  <option value="3">3</option>
  <option value="4">4</option>
  <option value="5">5</option>
  <option value="6">6</option>
  <option value="7">7</option>
  <option value="8">8</option>

  <option value="9">9</option>
  <option value="10">10</option>
</select>&nbsp;<label for="quantity">Select number of copies</label>
<br/>
<input type="image" src="http://www.paypal.com/en_GB/i/btn/sc-but-01.gif" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
<label for="submit">Purchase securely with PayPal</label>
<input type="hidden" name="add" value="1">
</form></br>
<p>&pound;15.95 plus P+P</p>
</div>

<p>Back to the <a href="index.php">list of titles</a>.</p>
