<h2>NEW in 2008 Mark Knight scales for Viola and Violin</h2>
<p>Now available: Carl Flesch Scales for Viola and Violin, Volumes I</a></p>
<table border="0">
<tr valign="top"><th align="left" valign="top"><a href="index.php?pageid=1.0">
		  <img src="images/images/mk6.jpg" height="180" alt="Carl Flesch Plus Scales for Viola Volume 1" border="0"/>
		  </th>
<td align="left" valign="top"></a><br/><a href="index.php?pageid=1.0"><h2>Carl Flesch Plus Scales for Viola Volume 1</h2></a><br/><br/>

<p>Double-Stop 3rds and 6ths in all keys. Collated and Fingered by Mark Knight</p><br/> <p class="details">£ 13.95 + postage and packing</p> <p class="details">ISMN:M 9002001-7-4</p> </td>
<td>
<form name="_xclick" target="paypal" action="https://www.paypal.co.uk/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_cart">
<input type="hidden" name="business" value="stringsattachedltd@googlemail.com">
<input type="hidden" name="currency_code" value="GBP">
<input type="hidden" name="item_name" value="Scales Viola Vol.1, ISMN:M 9002001-7-4">
<input type="hidden" name="amount" value="13.95">
<br/>
<select name="quantity">
  <option value="1">1</option>

  <option value="2">2</option>
  <option value="3">3</option>
  <option value="4">4</option>
  <option value="5">5</option>
  <option value="6">6</option>
  <option value="7">7</option>

  <option value="8">8</option>
  <option value="9">9</option>
  <option value="10">10</option>
</select>&nbsp;<label for="quantity">Select number of copies</label>
<br/>
<input type="image" src="http://www.paypal.com/en_GB/i/btn/sc-but-01.gif" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
<label for="submit">Purchase securely with PayPal</label>
<input type="hidden" name="add" value="1">
</form></br>

</td>
</tr>
<tr valign="top"><th align="left" valign="top"><a href="index.php?pageid=1.1">
		  <img src="images/images/mk7.jpg" height="180" alt="Carl Flesch Plus Scales for Violin Volume 1" border="0"/>
		  </th>
<td align="left" valign="top"></a><br/><a href="index.php?pageid=1.1"><h2>Carl Flesch Plus Scales for Violin Volume 1</h2></a><br/><br/>
<p>Double-Stop 3rds and 6ths in all keys. Collated and Fingered by Mark Knight</p><br/> <p class="details">£ 13.95 + postage and packing</p> <p class="details">ISMN:M 9002001-6-7</p> </td>
<td>

<form name="_xclick" target="paypal" action="https://www.paypal.co.uk/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_cart">
<input type="hidden" name="business" value="stringsattachedltd@googlemail.com">
<input type="hidden" name="currency_code" value="GBP">
<input type="hidden" name="item_name" value="Scales Violin Vol.1, ISMN:M 9002001-6-7">
<input type="hidden" name="amount" value="13.95">
<br/>
<select name="quantity">
  <option value="1">1</option>
  <option value="2">2</option>
  <option value="3">3</option>

  <option value="4">4</option>
  <option value="5">5</option>
  <option value="6">6</option>
  <option value="7">7</option>
  <option value="8">8</option>
  <option value="9">9</option>

  <option value="10">10</option>
</select>&nbsp;<label for="quantity">Select number of copies</label>
<br/>
<input type="image" src="http://www.paypal.com/en_GB/i/btn/sc-but-01.gif" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
<label for="submit">Purchase securely with PayPal</label>
<input type="hidden" name="add" value="1">
</form></br>
</td>
</tr>
</table><br/>
