<h2>Cadenzas for Haydn 'Cello Concerto in C Hob. VIIb:1</h2><p> by Mark Knight</p>
<p>Composed for his daughter Josephine Knight, (currently Principal 'Cello of the English Chamber Orchestra), the Haydn cadenzas are now published and available for purchase.</p>
<table class="book">
<tbody><tr>

<td><a class="popzoom" href=""><img src="images/images/mk4.jpg" onclick="javascript: pop_zoom('images/images/mk4.jpg','Cadenzas for Haydn 'Cello Concerto in C Hob. VIIb:1','ISMN: M 9002001-3-6',680,900);return false;" alt="Cadenzas for Haydn 'Cello Concerto in C Hob. VIIb:1" height="240">
<br><p>ISMN: M 9002001-3-6</p></a>
</td>
<td><a class="popzoom" href=""><img src="images/mknight_haydn_image_240_290_c.jpg" onclick="javascript: pop_zoom('images/mknight_haydn_image_240_290_c.jpg','Cadenzas for Haydn 'Cello Concerto in C Hob. VIIb:1','Illustration by Jackie Griffin',680,900);return false;" alt="Cadenzas for Haydn 'Cello Concerto in C Hob. VIIb:1" height="240">
<br><p>Illustration by Jackie Griffin</p></a>
</td>
<td><a class="popzoom" href=""><img src="image/viola1.sib" onclick="javascript: pop_zoom('image/viola1.sib','Cadenzas for Haydn 'Cello Concerto in C Hob. VIIb:1','Sample page Mark Knight',680,900);return false;" alt="Cadenzas for Haydn 'Cello Concerto in C Hob. VIIb:1" height="240">
<br><p>Sample page Mark Knight</p></a>
</td>
</tr></tbody></table>
<br>
<p>£7.95 + postage and packing</p> <p>ISMN:M 9002001-3-6<br>Illustration: Jackie Griffin</p>

<h2>Purchase with PayPal</h2>
<div class="PayPalPayNow">
<form name="_xclick" target="paypal" action="https://www.paypal.co.uk/cgi-bin/webscr" method="post">
<input name="cmd" value="_cart" type="hidden">
<input name="business" value="stringsattachedltd@googlemail.com" type="hidden">
<input name="currency_code" value="GBP" type="hidden">
<input name="item_name" value="Cadenza Haydn Cello, ISMN:M 9002001-3-6" type="hidden">
<input name="amount" value="7.95" type="hidden">
<br>
<select name="quantity">
  <option value="1">1</option>
  <option value="2">2</option>

  <option value="3">3</option>
  <option value="4">4</option>
  <option value="5">5</option>
  <option value="6">6</option>
  <option value="7">7</option>
  <option value="8">8</option>

  <option value="9">9</option>
  <option value="10">10</option>
</select>&nbsp;<label for="quantity">Select number of copies</label>
<br>
<input src="http://www.paypal.com/en_GB/i/btn/sc-but-01.gif" name="submit" alt="Make payments with PayPal - it's fast, free and secure!" border="0" type="image">
<label for="submit">Purchase securely with PayPal</label>
<input name="add" value="1" type="hidden">
</form><br>
<p>£7.95 plus P+P</p>
</div>

<p>Back to the <a href="index.php">list of titles</a>.</p>
