<h2>Cadenzas for Hoffmeister Viola Concerto in D</h2><p> by Mark Knight</p>
<p>Constructed from the composer's material as published by Kunzelmann (No. GM 701).</p>
<table class="book">
<tr>

<td><a class="popzoom" href=""><img src="images/images/mk2.jpg" onClick="javascript: pop_zoom('images/images/mk2.jpg','Cadenzas for Hoffmeister Viola Concerto in D','ISMN: M 9002001-2-9',680,900);return false;" alt="Cadenzas for Hoffmeister Viola Concerto in D" height="240"/>
<br/><p>ISMN: M 9002001-2-9</p></a>
</td>
<td><a class="popzoom" href=""><img src="images/mknight_hoffmeister_image_240_290.jpg" onClick="javascript: pop_zoom('images/mknight_hoffmeister_image_240_290.jpg','Cadenzas for Hoffmeister Viola Concerto in D','Illustration by Susan Bernhard-Brown',680,900);return false;" alt="Cadenzas for Hoffmeister Viola Concerto in D" height="240"/>
<br/><p>Illustration by Susan Bernhard-Brown</p></a>
</td>
<td><a class="popzoom" href=""><img src="images/cadenzas_hoffmeister_score_page_1.gif" onClick="javascript: pop_zoom('images/cadenzas_hoffmeister_score_page_1.gif','Cadenzas for Hoffmeister Viola Concerto in D','Sample page Mark Knight',680,900);return false;" alt="Cadenzas for Hoffmeister Viola Concerto in D" height="240"/>
<br/><p>Sample page Mark Knight</p></a>
</td>
</tr></table>
<br/>
<p>£9.95 + postage and packing</p> <p>ISMN:M 9002001-2-9<br/>Illustration: Susan Bernhard-Brown</p>

<h2>Purchase with PayPal</h2>
<div class="PayPalPayNow">
<form name="_xclick" target="paypal" action="https://www.paypal.co.uk/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_cart">
<input type="hidden" name="business" value="stringsattachedltd@googlemail.com">
<input type="hidden" name="currency_code" value="GBP">
<input type="hidden" name="item_name" value="Cadenza Hoffmeister, ISMN:M 9002001-2-9">
<input type="hidden" name="amount" value="9.95">
<br/>
<select name="quantity">
  <option value="1">1</option>
  <option value="2">2</option>

  <option value="3">3</option>
  <option value="4">4</option>
  <option value="5">5</option>
  <option value="6">6</option>
  <option value="7">7</option>
  <option value="8">8</option>

  <option value="9">9</option>
  <option value="10">10</option>
</select>&nbsp;<label for="quantity">Select number of copies</label>
<br/>
<input type="image" src="http://www.paypal.com/en_GB/i/btn/sc-but-01.gif" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
<label for="submit">Purchase securely with PayPal</label>
<input type="hidden" name="add" value="1">
</form></br>
<p>&pound;9.95 plus P+P</p>
</div>

<p>Back to the <a href="index.php">list of titles</a>.</p>
