<h2>NEW in 2008 Mark Knight scales for Viola and Violin</h2>
<p>Now available: <a href="index.php?pageid=1">Carl Flesch Scales for Viola and Violin, Volumes I</a></p>
<table border="0">
<tr valign="top"><th align="left" valign="top"><a href="index.php?pageid=0.0">
		  <img src="images/images/mk1.jpg" height="180" alt="Cadenzas for Carl Stamitz Viola Concerto No.1 in D, op.1" border="0"/>
		  </th>
<td align="left" valign="top"></a><br/><a href="index.php?pageid=0.0"><h2>Cadenzas for Carl Stamitz Viola Concerto No.1 in D, op.1</h2></a><br/><br/>

<p>Constructed from the text as published by Amadeus (BP 750).</p><br/> <p class="details">£ 9.95 + postage and packing</p> <p class="details">ISMN:M 9002001-1-2</p> </td>
<td>
<h5>Buy now with PayPal</h5>
<form name="_xclick" target="paypal" action="https://www.paypal.co.uk/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_cart">
<input type="hidden" name="business" value="stringsattachedltd@googlemail.com">
<input type="hidden" name="currency_code" value="GBP">
<input type="hidden" name="item_name" value="Cadenza Stamitz, ISMN:M 9002001-1-2">
<input type="hidden" name="amount" value="9.95">
<br/>

<select name="quantity">
  <option value="1">1</option>
  <option value="2">2</option>
  <option value="3">3</option>
  <option value="4">4</option>
  <option value="5">5</option>
  <option value="6">6</option>

  <option value="7">7</option>
  <option value="8">8</option>
  <option value="9">9</option>
  <option value="10">10</option>
</select>&nbsp;<label for="quantity">Select number of copies</label>
<br/>
<input type="image" src="http://www.paypal.com/en_GB/i/btn/sc-but-01.gif" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
<label for="submit">Purchase securely with PayPal</label>

<input type="hidden" name="add" value="1">
</form></br>
</td>
</tr>
<tr valign="top"><th align="left" valign="top"><a href="index.php?pageid=0.1">
		  <img src="images/images/mk2.jpg" height="180" alt="Cadenzas for Hoffmeister Viola Concerto in D" border="0"/>
		  </th>
<td align="left" valign="top"></a><br/><a href="index.php?pageid=0.1"><h2>Cadenzas for Hoffmeister Viola Concerto in D</h2></a><br/><br/>
<p>Constructed from the composer's material as published by Kunzelmann (No. GM 701).</p><br/> <p class="details">£ 9.95 + postage and packing</p> <p class="details">ISMN:M 9002001-2-9</p> </td>

<td>
<h5>Buy now with PayPal</h5>
<form name="_xclick" target="paypal" action="https://www.paypal.co.uk/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_cart">
<input type="hidden" name="business" value="stringsattachedltd@googlemail.com">
<input type="hidden" name="currency_code" value="GBP">
<input type="hidden" name="item_name" value="Cadenza Hoffmeister, ISMN:M 9002001-2-9">
<input type="hidden" name="amount" value="9.95">
<br/>
<select name="quantity">
  <option value="1">1</option>
  <option value="2">2</option>

  <option value="3">3</option>
  <option value="4">4</option>
  <option value="5">5</option>
  <option value="6">6</option>
  <option value="7">7</option>
  <option value="8">8</option>

  <option value="9">9</option>
  <option value="10">10</option>
</select>&nbsp;<label for="quantity">Select number of copies</label>
<br/>
<input type="image" src="http://www.paypal.com/en_GB/i/btn/sc-but-01.gif" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
<label for="submit">Purchase securely with PayPal</label>
<input type="hidden" name="add" value="1">
</form></br>
</td>
</tr>
<tr valign="top"><th align="left" valign="top"><a href="index.php?pageid=0.2">

		  <img src="images/images/mk3.jpg" height="180" alt="Cadenzas for Mozart Violin Concertos No.1 in B flat K207 & No.2 in D, K211" border="0"/>
		  </th>
<td align="left" valign="top"></a><br/><a href="index.php?pageid=0.2"><h2>Cadenzas for Mozart Violin Concertos No.1 in B flat K207 & No.2 in D, K211</h2></a><br/><br/>
<p>Constructed from Mozart's text as printed in the "Urtext of the New Mozart Edition" published by B&auml;renreiter (BA4864a).</p><br/> <p class="details">£ 12.95 + postage and packing</p> <p class="details">ISMN:M 9002001-0-5</p> </td>
<td>
<h5>Buy now with PayPal</h5>

<form name="_xclick" target="paypal" action="https://www.paypal.co.uk/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_cart">
<input type="hidden" name="business" value="stringsattachedltd@googlemail.com">
<input type="hidden" name="currency_code" value="GBP">
<input type="hidden" name="item_name" value="Cadenza Mozart, ISMN:M 9002001-0-5">
<input type="hidden" name="amount" value="12.95">
<br/>
<select name="quantity">
  <option value="1">1</option>
  <option value="2">2</option>
  <option value="3">3</option>

  <option value="4">4</option>
  <option value="5">5</option>
  <option value="6">6</option>
  <option value="7">7</option>
  <option value="8">8</option>
  <option value="9">9</option>

  <option value="10">10</option>
</select>&nbsp;<label for="quantity">Select number of copies</label>
<br/>
<input type="image" src="http://www.paypal.com/en_GB/i/btn/sc-but-01.gif" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
<label for="submit">Purchase securely with PayPal</label>
<input type="hidden" name="add" value="1">
</form></br>
</td>
</tr>
<tr valign="top"><th align="left" valign="top"><a href="index.php?pageid=0.3">
		  <img src="images/images/mk4.jpg" height="180" alt="Cadenzas for Haydn Cello Concerto in C Hob. VIIb:1" border="0"/>
		  </th>

<td align="left" valign="top"></a><br/><a href="index.php?pageid=0.3"><h2>Cadenzas for Haydn Cello Concerto in C Hob. VIIb:1</h2></a><br/><br/>
<p>Composed for his daughter Josephine Knight, (currently Principal Cello of the English Chamber Orchestra), the Haydn cadenzas are now published and available for purchase.</p><br/> <p class="details">£ 7.95 + postage and packing</p> <p class="details">ISMN:M 9002001-3-6</p> </td>
<td>
<h5>Buy now with PayPal</h5>
<form name="_xclick" target="paypal" action="https://www.paypal.co.uk/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_cart">
<input type="hidden" name="business" value="stringsattachedltd@googlemail.com">
<input type="hidden" name="currency_code" value="GBP">
<input type="hidden" name="item_name" value="Cadenza Haydn Cello, ISMN:M 9002001-3-6">

<input type="hidden" name="amount" value="7.95">
<br/>
<select name="quantity">
  <option value="1">1</option>
  <option value="2">2</option>
  <option value="3">3</option>
  <option value="4">4</option>
  <option value="5">5</option>

  <option value="6">6</option>
  <option value="7">7</option>
  <option value="8">8</option>
  <option value="9">9</option>
  <option value="10">10</option>
</select>&nbsp;<label for="quantity">Select number of copies</label>

<br/>
<input type="image" src="http://www.paypal.com/en_GB/i/btn/sc-but-01.gif" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
<label for="submit">Purchase securely with PayPal</label>
<input type="hidden" name="add" value="1">
</form></br>
</td>
</tr>
<tr valign="top"><th align="left" valign="top"><a href="index.php?pageid=0.4">
		  <img src="images/images/mk5.jpg" height="180" alt="Concerto in C major for Viola, Haydn Hob.VIIb:1" border="0"/>
		  </th>
<td align="left" valign="top"></a><br/><a href="index.php?pageid=0.4"><h2>Concerto in C major for Viola, Haydn Hob.VIIb:1</h2></a><br/><br/>
<p>Mark Knight's transcription of Haydn's Cello Concerto in C for viola, complete with cadenzas.</p><br/> <p class="details">£ 15.95 + postage and packing</p> <p class="details">ISMN:M 9002001-5-0</p> </td>

<td>
<h5>Buy now with PayPal</h5>
<form name="_xclick" target="paypal" action="https://www.paypal.co.uk/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_cart">
<input type="hidden" name="business" value="stringsattachedltd@googlemail.com">
<input type="hidden" name="currency_code" value="GBP">
<input type="hidden" name="item_name" value="Cadenza Haydn Viola, ISMN:M 9002001-5-0">
<input type="hidden" name="amount" value="15.95">
<br/>
<select name="quantity">
  <option value="1">1</option>
  <option value="2">2</option>

  <option value="3">3</option>
  <option value="4">4</option>
  <option value="5">5</option>
  <option value="6">6</option>
  <option value="7">7</option>
  <option value="8">8</option>

  <option value="9">9</option>
  <option value="10">10</option>
</select>&nbsp;<label for="quantity">Select number of copies</label>
<br/>
<input type="image" src="http://www.paypal.com/en_GB/i/btn/sc-but-01.gif" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
<label for="submit">Purchase securely with PayPal</label>
<input type="hidden" name="add" value="1">
</form></br>
</td>
</tr>
<tr>

<td>&nbsp;</td>
<td>&nbsp;</td>
<td>
</td>
</tr>
</table>
<br/>

