<h2>Carl Flesch Plus Scales for Violin Volume 1</h2><p> by Mark Knight</p>
<p>Double-Stop 3rds and 6ths in all keys. Collated and Fingered by Mark Knight</p>
<table class="book">
<tr>

<td><a class="popzoom" href=""><img src="images/images/mk7.jpg" onClick="javascript: pop_zoom('images/images/mk7.jpg','Carl Flesch Plus Scales for Violin Volume 1','ISMN: M 9002001-6-7',680,900);return false;" alt="Carl Flesch Plus Scales for Violin Volume 1, images/images/mk7.jpg" height="240"/>
<br/><p>ISMN: M 9002001-6-7</p></a>
</td>
<td><a class="popzoom" href=""><img src="images/20080515/Violin.jpg" onClick="javascript: pop_zoom('images/20080515/Violin.jpg','Carl Flesch Plus Scales for Violin Volume 1','Illustration by MK',680,900);return false;" alt="Carl Flesch Plus Scales for Violin Volume 1, images/20080515/Violin.jpg" height="240"/>
<br/><p>Illustration by MK</p></a>
</td>
<td><a class="popzoom" href=""><img src="images/images/scales_violin_sample.jpg" onClick="javascript: pop_zoom('images/images/scales_violin_sample.jpg','Carl Flesch Plus Scales for Violin Volume 1','Sample page Mark Knight',680,900);return false;" alt="Carl Flesch Plus Scales for Violin Volume 1, images/images/scales_violin_sample.jpg" height="240"/>
<br/><p>Sample page Mark Knight</p></a>
</td>
</tr></table>
<br/>
<p>£13.95 + postage and packing</p> <p>ISMN:M 9002001-6-7<br/>Illustration: MK</p>

<h2>Purchase with PayPal</h2>
<div class="PayPalPayNow">
<form name="_xclick" target="paypal" action="https://www.paypal.co.uk/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_cart">
<input type="hidden" name="business" value="stringsattachedltd@googlemail.com">
<input type="hidden" name="currency_code" value="GBP">
<input type="hidden" name="item_name" value="Scales Violin Vol.1, ISMN:M 9002001-6-7">
<input type="hidden" name="amount" value="13.95">
<br/>
<select name="quantity">
  <option value="1">1</option>
  <option value="2">2</option>

  <option value="3">3</option>
  <option value="4">4</option>
  <option value="5">5</option>
  <option value="6">6</option>
  <option value="7">7</option>
  <option value="8">8</option>

  <option value="9">9</option>
  <option value="10">10</option>
</select>&nbsp;<label for="quantity">Select number of copies</label>
<br/>
<input type="image" src="http://www.paypal.com/en_GB/i/btn/sc-but-01.gif" border="0" name="submit" alt="Make payments with PayPal - it's fast, free and secure!">
<label for="submit">Purchase securely with PayPal</label>
<input type="hidden" name="add" value="1">
</form></br>
<p>&pound;13.95 plus P+P</p>
</div>

<p>Back to the <a href="index.php">list of titles</a>.</p>

