<h1>Please complete the form below</h1>

<p>Please check your order and complete the form on this page. We will send you an email containing your order details including how to make your payment.</p>

<p>Please note that we can only accept cheques in UK currency (GBP pounds Sterling.)</p>

<p>On receipt of the full payment for your order, (including postage and packing) we will send your order to you.</p>

<p>Please note it is important that you give full and complete address details (including you postal code or zip code) so that we can ensure your order reaches you.</p>

<p>Your phone number is optional, however should we have any difficulties with your order, it is useful if we can contact you to advise of this.</p>

<p>Thank you for shopping with cadenzas.com.</p>
