<h1>All publications are available for purchase using PayPal, or by Mail Order</h1>

<p>If you would like to place an order and pay by cheque (UK Currency GB Pounds Sterling only), please select the quantity of each item you wish to purchase and click the "purchase" button. You will then see a summary of your order, and a form for you to enter delivery details. You may amend your order at this stage. When you are happy with your order please complete the form and click the "submit" button.
</p>
<br/>

<p>
You will be sent an email containing a summary of your order and detailed instructions on how to send payment to us. Please note that only on receipt of all the required and correct details on the form, accompanied by a cheque in the correct amount, (including the correct payment for postage and packing) can we forward the publications to you.</p>
<br/>


<p>Thank you for shopping with cadenzas.com.</p>
