<h2>Haydn</h2>
<p>
Mark Knight's transcription of Haydn's 'Cello Concerto in C Hob. VIIb:1 for viola, complete with cadenzas is now published and available for purchase. 
</p>
<p>
An Urtext part is provided for study and comparison with the editorial decisions. The sources for the transcription and cadenzas are B&auml;renreiter's study score (TP291) and the Henle 'Cello and Piano edition (417) which is recommended as the most appropriate piano reduction accompaniment for rehearsal.
</p>
<h5>Mark Knight</h5>

