<h1>All publications are available for purchase from the Spartan Press website </h1>

<p><a href="http://www.spartanpress.co.uk">Spartan Press</a></p>

<p>To purchase using a credit or debit card, please select and click the "Purchase now" link to Spartan Press where you will be able to buy online.</p> 

<br/>

<p>Please note that your order will be sent using Royal Mail from the UK. You should receive the items within the delivery period specified by the Royal Mail, with an additional business day allowed for Spartan Press to process your order.
</p>
<br/>
<p>Thank you for visiting Cadenzas.com.</p>
<br/>

