<h2>Carl Stamitz</h2>
<p>
Carl Stamitz (1745-1801), son of Johann and elder brother of Anton, was the most distinguished member of this noted musical family who were deeply associated with the Mannheim School of composition. He had a successful career as a solo violinist and orchestral director but his most important contribution has been as a composer for the viola, an instrument which he often played as a soloist all over Europe as part of his extensive concert touring. Other than this Viola Concerto in D, very few of his chamber, symphonic or concertante works are performed now but their influence upon his great contemporaries is undeniable, in spite of Mozart's scathing remarks about the Stamitz brothers in a letter to his father in 1778.
</p>
<p>
Mozart was writing from Paris where Carl Stamitz had become established since 1770. The viola Concerto in D, Op.1 was composed during this period, no doubt for his own use as a piece to display his virtuosity, confirmed by the exploitation of multiple stopping, pedal notes, harmonics and even a left-hand pizzicato thereby anticipating Paganini by forty years.
</p>
<p>
These cadenzas are constructed entirely from the text as published by Amadeus (BP 750, 1995) which is recommended as a thorough and scholarly edition prepared in the absence of an autograph of the solo part. Although some performance guidance is provided, it is anticipated that a performer would respond personally in the spirit of an improvisation, as was the practice of performers in the late eighteenth century, and that the chosen articulation in a performance would match that of the parallel passages in the Concerto.
</p>
<h5>Mark Knight</h5> 
