<h2>Carl Flesch Scales System</h2>
<p>
For several decades the "Carl Flesch Scales System" for both violin and viola has been a central technical manual for aspiring, advanced and professional players and teachers of these string instruments. However it has become increasingly clear that the "system" needs upgrading for 21st Century applications, and the opportunity has been taken to clarify the essential principles that Flesch outlines in his "Art of Violin Playing" to which the Scale System was an explanatory and practise supplement.
</p>
<p>
Volume I, a practice manual will soon be followed by Volume II, which relates the fingering principles, which lie at the core of this project, to examination presentation. Students and teachers will welcome a publication which links the Flesch scale manual to practical requirements of contemporary examinations, especially in the music colleges.
</p>
