<h2>Contact Mark Knight</h2>


<p>For information on the work of Mark Knight and all materials published by Strings Attached Ltd, contact</p>
<strong>Strings Attached Ltd.<br>Great Skewes Cottage<br>St. Wenn<br>Bodmin<br>Cornwall<br>PL30 5PS<br>United Kingdom<br> Telephone and Fax: +44 (0)1726 890 639
</strong>

<br />
<br />

<h4> Distributed exclusively by:</h4>
<strong>
Spartan Press
<br />
Strathmashie House
<br />
Laggan
<br />
PH20 1BU
<br />
United Kingdom
<br />
Tel: +44(0)1528 544770
<br />
Fax: +44(0)1528 544770
<br />
Email: <a href="mailto:sales@spartanpress.co.uk">sales@spartanpress.co.uk </a>
<br />
Web: <a href="http://www.SpartanPress.co.uk"> www.spartanpress.co.uk </a>
</strong>

<img src="images/mknight1_200.jpg" alt="Mark Knight" align="right" width="200" height="196"><br clear="all">
<p class="smallText" align="right"> Photo: Janet Young </p>
