<h1>Forthcoming Publications</h1>
<ul>
<li>
Cadenzas for Mozart Horn Concertos in E flat, K.495 and K447 for both French horn and natural horn</li>
</ul>

<h1>Other Publications</h1>
<ul>
<li>Kreutzer - 42 Etudes, ed. Mark Knight, pub. Stainer & Bell</li>
<li>Corelli - Violin Sonatas Op.5, ed. Mark Knight, pub. Stainer & Bell</li>
<li>Geoffrey Burgon - Six Studies for Solo Viola (transcribed from 'cello by Mark Knight) pub. Chester & Co., London</li>
</ul>
