<h2>Hoffmeister</h2>
<p>
Franz Anton Hoffmeister (1754-1812) was a music publisher as well as a composer. He was a friend of both Haydn and Mozart, the latter dedicating his String Quartet in D K499 to him in recognition of his support in publishing several first editions.
</p>
<p>
As a composer Hoffmeister was prolific, his works spanning virtually all <i>genres</i> from small scale chamber music through symphonies to opera. His music was admired during his lifetime for its melodic content and as models for study. Apart from the Concerto in D for Viola little of his music is now performed but this work has established itself as one of the principal classical concertos for the instrument.
</p>
<p>
These cadenzas have been constructed from the composer's material as published by Kunzelmann (No. GM 701) in an edition prepared by Ulrich Dr&uuml;ner in the absence of an autograph. It is unfortunate that this scholarly attempt at revealing the composer's intentions has been undermined by the printing of several wrong notes (eg 3rd movement, bar 36.) Neverthless this edition is recommended as the basis for preparation of a performance and it is to this edition that the bar numbers at the beginnings and ends of the cadenzas apply. Only dots, instead of dots and wedges of the Kunzelmann Edition, have been employed for articulation indications as it is assumed that in performance the choice of bow stroke will match that chosen for the parallel passages in the concerto. Performance guidance has been provided but personal response is entirely appropriate in the context of what would have been an improvisation by the soloist.
</p>
<h5>Mark Knight</h5>
