<h2>Mozart</h2>
<p>
Mozart wrote the B flat major Violin Concerto, K207, in 1773 and the D major Concerto, K211, in 1775, probably for his own use. It is known that at this time Mozart was active as a violinist. Both works have been neglected although the "little" D major Concerto is occasionally played in public. One reason for their relative neglect may be the absence of readily accessible cadenzas especially as our increasing understanding of the 18th century performance practice demonstrates the need for improvisatory material at fermatas throughout the concertos in addition to the traditionally understood place at the ends of the first and second movements.
</p>
<p>
These cadenzas have been constructed from Mozart's text as printed in the "Urtext of the new Mozart Edition" published by B&auml;renreiter. The bar numbers at the beginnings and ends of these cadenzas relate to the B&auml;renreiter editions which are strongly recommended as a reliable source for study and preparation.
</p>
<p>
Although performance instructions are included, it is anticipated that the violinist will interpret these cadenzas with imagination and personal response, without necessarily following the dynamic and tempo markings. Articulation has been indicated by the use of dots rather than dots and wedges which are to be found in B&auml;renreiter texts. The degree and style of articulation in the performance of these cadenzas should relate to the way in which Mozart's passage work is played.
</p>
<h5>Mark Knight</h5>
